# Questions



1. Import the dataset – Airbab New York data AB_NYC_2019.csv
2. How many rows and columns are there in the dataset?
3. Print the column names
4. Print some sample rows from the data
5. What are the column data types? 
6. Are there any missing values in the data? 
7. Create a new dataset by considering only numerical columns. 
8. Create a new dataset by considering only Non-numerical columns.
9. Create a subset by considering only room_type=“Private room”
10. Create a subset by considering only room_type="Private room" and "price" < 100
11. Sort the data based on number_of_reviews. Both ascending and descending 
12. Sort the data by price descending and by number_of_reviews on a tie 
13. Sort the data by price descending and select first ten rows. 
14. Drop the id column from the data crate a new dataset.
15. Create a new column in the data, discount_price = price*0.75
16. Shuffle the data - Create a new column , fill it with random numbers between 1 to 10, then sort the data based on this column. 
17. Are there any duplicate rows in the overall dataset?, if yes how many?
18. Are there any duplicates based on host_id?
19. Import the AB_NYC_2019_Reviews.csv data. Attach ratings data to the input data. 
20. Export the above merged data into a csv file

# Data Importing

In [89]:
import pandas as pd
input_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/python_5days/master/Day2_Files/Datasets/AB_NYC_2019.csv")

In [5]:
print(input_data)

             id  ... availability_365
0          2539  ...              365
1          2595  ...              355
2          3647  ...              365
3          3831  ...              194
4          5022  ...                0
...         ...  ...              ...
48890  36484665  ...                9
48891  36485057  ...               36
48892  36485431  ...               27
48893  36485609  ...                2
48894  36487245  ...               23

[48895 rows x 16 columns]

## Importing from excel files

In [6]:
input_data1=pd.read_excel("https://raw.githubusercontent.com/venkatareddykonasani/python_5days/master/Day2_Files/Datasets/AB_NYC_2019.xlsx")

In [7]:
print(input_data1)

                                             Context
0  Since 2008, guests and hosts have used Airbnb ...
1                                            Content
2  This data file includes all needed information...
3                                   Acknowledgements
4  This public dataset is part of Airbnb, and the...
5                                        Inspiration
6  What can we learn about different hosts and ar...
7  What can we learn from predictions? (ex: locat...
8               Which hosts are the busiest and why?
9  Is there any noticeable difference of traffic ...

In [8]:
input_data1=pd.read_excel("https://raw.githubusercontent.com/venkatareddykonasani/python_5days/master/Day2_Files/Datasets/AB_NYC_2019.xlsx", sheet_name="AB_NYC_2019")

In [9]:
print(input_data1)

             id  ... availability_365
0          2539  ...              365
1          2595  ...              355
2          3647  ...              365
3          3831  ...              194
4          5022  ...                0
...         ...  ...              ...
48890  36484665  ...                9
48891  36485057  ...               36
48892  36485431  ...               27
48893  36485609  ...                2
48894  36487245  ...               23

[48895 rows x 16 columns]

# Basic Commands

In [11]:
#How many rows and columns are there in the dataset?
input_data.shape

(48895, 16)

In [12]:
input_data.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [13]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

# Printing sample data

In [15]:
input_data.sample(10)

             id  ... availability_365
48131  36103759  ...               30
12594   9682862  ...                0
37964  30014004  ...                8
26982  21367482  ...               22
20826  16493057  ...                0
41665  32399523  ...              281
17548  13801296  ...                0
20325  16241319  ...                0
37645  29852434  ...              177
45232  34620353  ...               83

[10 rows x 16 columns]

In [16]:
input_data.head(10)

     id  ... availability_365
0  2539  ...              365
1  2595  ...              355
2  3647  ...              365
3  3831  ...              194
4  5022  ...                0
5  5099  ...              129
6  5121  ...                0
7  5178  ...              220
8  5203  ...                0
9  5238  ...              188

[10 rows x 16 columns]

In [17]:
input_data.tail(10)

             id  ... availability_365
48885  36482809  ...              353
48886  36483010  ...              176
48887  36483152  ...              365
48888  36484087  ...               31
48889  36484363  ...              163
48890  36484665  ...                9
48891  36485057  ...               36
48892  36485431  ...               27
48893  36485609  ...                2
48894  36487245  ...               23

[10 rows x 16 columns]

In [18]:
print(input_data.head())

     id  ... availability_365
0  2539  ...              365
1  2595  ...              355
2  3647  ...              365
3  3831  ...              194
4  5022  ...                0

[5 rows x 16 columns]

In [23]:
pd.set_option("display.max_columns", None)
print(input_data.head())

     id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787
1  2595                             Skylit Midtown Castle     2845
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632
3  3831                   Cozy Entire Floor of Brownstone     4869
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976
4        Laura           Manhattan   East Harlem  40.79851  -73.94399

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19
1  Entire home/apt    225               1                 45  2019-05-21
2     Private room    150               3                  0         NaN
3  Entire home/apt     89               1                270  2019-07-05
4  Entire home/apt     80              10                  9  2018-11-19

   reviews_per_month  calculated_host_listings_count  availability_365
0               0.21                               6               365
1               0.38                               2               355
2                NaN                               1               365
3               4.64                               1               194
4               0.10                               1                 0

In [25]:
pd.set_option("display.max_columns", None)
print(input_data.head())

     id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787
1  2595                             Skylit Midtown Castle     2845
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632
3  3831                   Cozy Entire Floor of Brownstone     4869
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976
4        Laura           Manhattan   East Harlem  40.79851  -73.94399

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19
1  Entire home/apt    225               1                 45  2019-05-21
2     Private room    150               3                  0         NaN
3  Entire home/apt     89               1                270  2019-07-05
4  Entire home/apt     80              10                  9  2018-11-19

   reviews_per_month  calculated_host_listings_count  availability_365
0               0.21                               6               365
1               0.38                               2               355
2                NaN                               1               365
3               4.64                               1               194
4               0.10                               1                 0

#Data Types

In [26]:
input_data.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [27]:
input_data["host_id"].dtypes

dtype('int64')

In [28]:
[[col, input_data[col].dtypes]  for col in input_data.columns]

[['id', dtype('int64')],
 ['name', dtype('O')],
 ['host_id', dtype('int64')],
 ['host_name', dtype('O')],
 ['neighbourhood_group', dtype('O')],
 ['neighbourhood', dtype('O')],
 ['latitude', dtype('float64')],
 ['longitude', dtype('float64')],
 ['room_type', dtype('O')],
 ['price', dtype('int64')],
 ['minimum_nights', dtype('int64')],
 ['number_of_reviews', dtype('int64')],
 ['last_review', dtype('O')],
 ['reviews_per_month', dtype('float64')],
 ['calculated_host_listings_count', dtype('int64')],
 ['availability_365', dtype('int64')]]

In [29]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

# Missing values

In [30]:
input_data.isnull()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48891,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48892,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48893,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
48894,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False

In [31]:
sum(input_data.isnull())

TypeError: ignored

In [32]:
sum(input_data["id"].isnull())

0

In [33]:
sum(input_data["name"].isnull())

16

In [34]:
[[col, sum(input_data[col].isnull())] for col in input_data.columns]

[['id', 0],
 ['name', 16],
 ['host_id', 0],
 ['host_name', 21],
 ['neighbourhood_group', 0],
 ['neighbourhood', 0],
 ['latitude', 0],
 ['longitude', 0],
 ['room_type', 0],
 ['price', 0],
 ['minimum_nights', 0],
 ['number_of_reviews', 0],
 ['last_review', 10052],
 ['reviews_per_month', 10052],
 ['calculated_host_listings_count', 0],
 ['availability_365', 0]]

In [35]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

# Selecting columns

In [36]:
input_data.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [38]:
numeric_cols=["id", "host_id"]
numeric_cols_data=input_data[numeric_cols]
print(numeric_cols_data.shape)
print(numeric_cols_data.head())

(48895, 2)
     id  host_id
0  2539     2787
1  2595     2845
2  3647     4632
3  3831     4869
4  5022     7192

In [42]:
all_numeric_cols=[col for col in input_data.columns if input_data[col].dtypes in ["int64","float64"]]
print(all_numeric_cols)
print(len(all_numeric_cols))

['id', 'host_id', 'latitude', 'longitude', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']
10

In [43]:
numeric_cols_data=input_data[all_numeric_cols]
print(numeric_cols_data.shape)
print(numeric_cols_data.head())

(48895, 10)
     id  host_id  latitude  longitude  price  minimum_nights  \
0  2539     2787  40.64749  -73.97237    149               1
1  2595     2845  40.75362  -73.98377    225               1
2  3647     4632  40.80902  -73.94190    150               3
3  3831     4869  40.68514  -73.95976     89               1
4  5022     7192  40.79851  -73.94399     80              10

   number_of_reviews  reviews_per_month  calculated_host_listings_count  \
0                  9               0.21                               6
1                 45               0.38                               2
2                  0                NaN                               1
3                270               4.64                               1
4                  9               0.10                               1

   availability_365
0               365
1               355
2               365
3               194
4                 0

In [44]:
object_cols=[col for col in input_data.columns if input_data[col].dtypes in ["object"]]
print(object_cols)
print(len(object_cols))

['name', 'host_name', 'neighbourhood_group', 'neighbourhood', 'room_type', 'last_review']
6

In [45]:
object_cols_data=input_data[object_cols]
print(object_cols_data.shape)
print(object_cols_data.head())

(48895, 6)
                                               name    host_name  \
0                Clean & quiet apt home by the park         John
1                             Skylit Midtown Castle     Jennifer
2               THE VILLAGE OF HARLEM....NEW YORK !    Elisabeth
3                   Cozy Entire Floor of Brownstone  LisaRoxanne
4  Entire Apt: Spacious Studio/Loft by central park        Laura

  neighbourhood_group neighbourhood        room_type last_review
0            Brooklyn    Kensington     Private room  2018-10-19
1           Manhattan       Midtown  Entire home/apt  2019-05-21
2           Manhattan        Harlem     Private room         NaN
3            Brooklyn  Clinton Hill  Entire home/apt  2019-07-05
4           Manhattan   East Harlem  Entire home/apt  2018-11-19

# Subsets

In [46]:
#Create a subset by considering only room_type=“Private room”
#Create a subset by considering only room_type="Private room" and "price" < 100

In [47]:
#Unique values inside a column
input_data["room_type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

In [50]:
private_room_data=input_data[input_data["room_type"]=="Private room"]
print(private_room_data.shape)

(22326, 16)

In [52]:
private_room_data1=input_data[(input_data["room_type"]=="Private room") & (input_data["price"]<100)]
print(private_room_data1.shape)

(17258, 16)

# Sorting the data

In [ ]:
#Sort the data based on number_of_reviews. Both ascending and descending
#Sort the data by price descending and by number_of_reviews on a tie
#Sort the data by price descending and select first ten rows.

In [53]:
input_data_sort=input_data.sort_values(by=["number_of_reviews"])
input_data_sort.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23
28711,22204856,Room available in 3 BD Brooklyn apartment,1819657,Eleanor,Brooklyn,Clinton Hill,40.68381,-73.96786,Private room,55,2,0,NaN,NaN,1,0
15661,12650830,Quiet room in Bed-Stuy,68585649,Joseph,Brooklyn,Bedford-Stuyvesant,40.69186,-73.94038,Private room,30,80,0,NaN,NaN,1,0
40011,31076156,长岛豪华公寓单间卧室低价短租交通无敌便利,232169947,辣辣,Queens,Long Island City,40.74779,-73.93820,Private room,60,2,0,NaN,NaN,1,0
7707,5826468,Large 2 bed 2 bath w private patio!,27894798,Aya,Manhattan,East Harlem,40.79372,-73.94316,Entire home/apt,200,30,0,NaN,NaN,1,0

In [54]:
input_data_sort=input_data.sort_values(by=["number_of_reviews"], ascending= False)
input_data_sort.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
11759,9145202,Room near JFK Queen Bed,47621202,Dona,Queens,Jamaica,40.66730,-73.76831,Private room,47,1,629,2019-07-05,14.58,2,333
2031,903972,Great Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82085,-73.94025,Private room,49,1,607,2019-06-21,7.75,3,293
2030,903947,Beautiful Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82124,-73.93838,Private room,49,1,597,2019-06-23,7.72,3,342
2015,891117,Private Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82264,-73.94041,Private room,49,1,594,2019-06-15,7.57,3,339
13495,10101135,Room Near JFK Twin Beds,47621202,Dona,Queens,Jamaica,40.66939,-73.76975,Private room,47,1,576,2019-06-27,13.40,2,173

In [55]:
input_data_sort2=input_data.sort_values(by=["price", "number_of_reviews"],ascending= [False, False])
input_data_sort2.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
17692,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.16,1,0
9151,7003697,Furnished room in Astoria apartment,20582832,Kathrine,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,2016-02-13,0.04,1,0
29238,22436899,1-BR Lincoln Center,72390391,Jelena,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,NaN,NaN,1,83
12342,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,2016-01-01,0.14,1,83
6530,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.02,1,0

In [56]:
input_data_sort3=input_data.sort_values(by=["price"],ascending=[False])
input_data_sort3

input_data_first_ten=input_data_sort3.head(10)
input_data_first_ten

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
9151,7003697,Furnished room in Astoria apartment,20582832,Kathrine,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,2016-02-13,0.04,1,0
17692,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.16,1,0
29238,22436899,1-BR Lincoln Center,72390391,Jelena,Manhattan,Upper West Side,40.77213,-73.98665,Entire home/apt,10000,30,0,NaN,NaN,1,83
40433,31340283,2br - The Heart of NYC: Manhattans Lower East ...,4382127,Matt,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,NaN,NaN,1,365
12342,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,2016-01-01,0.14,1,83
6530,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.02,1,0
30268,23377410,Beautiful/Spacious 1 bed luxury flat-TriBeCa/Soho,18128455,Rum,Manhattan,Tribeca,40.72197,-74.00633,Entire home/apt,8500,30,2,2018-09-18,0.18,1,251
4377,2953058,Film Location,1177497,Jessica,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,2016-09-15,0.03,11,365
29662,22779726,East 72nd Townhouse by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper East Side,40.76824,-73.95989,Entire home/apt,7703,1,0,NaN,NaN,12,146
42523,33007610,70' Luxury MotorYacht on the Hudson,7407743,Jack,Manhattan,Battery Park City,40.71162,-74.01693,Entire home/apt,7500,1,0,NaN,NaN,1,364

# Index location - iloc

In [57]:
input_data_first_few_rows=input_data.iloc[range(0,5)]
input_data_first_few_rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [58]:
input_data_few_rows=input_data.iloc[[1,3,5,7,9]]
input_data_few_rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
7,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220
9,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188

In [59]:
rows_to_select=[1,3,5,7,9]
input_data_few_rows=input_data.iloc[rows_to_select]
input_data_few_rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
7,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220
9,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188

In [60]:
input_data.index

RangeIndex(start=0, stop=48895, step=1)

## iloc for rows and columns

In [61]:
subset_by_index=input_data.iloc[0:10, 0:3]
subset_by_index

     id                                              name  host_id
0  2539                Clean & quiet apt home by the park     2787
1  2595                             Skylit Midtown Castle     2845
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632
3  3831                   Cozy Entire Floor of Brownstone     4869
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192
5  5099         Large Cozy 1 BR Apartment In Midtown East     7322
6  5121                                   BlissArtsSpace!     7356
7  5178                  Large Furnished Room Near B'way      8967
8  5203                Cozy Clean Guest Room - Family Apt     7490
9  5238                Cute & Cozy Lower East Side 1 bdrm     7549

In [62]:
subset_by_index=input_data.iloc[:, 0:3]
subset_by_index

             id                                               name   host_id
0          2539                 Clean & quiet apt home by the park      2787
1          2595                              Skylit Midtown Castle      2845
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632
3          3831                    Cozy Entire Floor of Brownstone      4869
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192
...         ...                                                ...       ...
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630
48892  36485431            Sunny Studio at Historical Neighborhood  23492952
48893  36485609               43rd St. Time Square-cozy single bed  30985759
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814

[48895 rows x 3 columns]

In [65]:
subset_by_index=input_data.iloc[0:5, [1,5,6,7]]
subset_by_index

,name,neighbourhood,latitude,longitude
0,Clean & quiet apt home by the park,Kensington,40.64749,-73.97237
1,Skylit Midtown Castle,Midtown,40.75362,-73.98377
2,THE VILLAGE OF HARLEM....NEW YORK !,Harlem,40.80902,-73.94190
3,Cozy Entire Floor of Brownstone,Clinton Hill,40.68514,-73.95976
4,Entire Apt: Spacious Studio/Loft by central park,East Harlem,40.79851,-73.94399

# Drop rows and Columns

In [67]:
print("input data shape", input_data.shape)
data_after_rows_drop=input_data.drop([0,1,2,3,4,5], axis=0)
print("data_after_rows_drop shape", data_after_rows_drop.shape)

input data shape (48895, 16)
data_after_rows_drop shape (48889, 16)

In [69]:
print("input data shape", input_data.shape)
data_after_cols_drop=input_data.drop(["name","neighbourhood_group"], axis=1)
print("data_after_cols_drop shape", data_after_cols_drop.shape)

input data shape (48895, 16)
data_after_cols_drop shape (48895, 14)

# Creating new columns

In [71]:
#Create a new column in the data, discount_price = price*0.75
print("input data shape", input_data.shape)
input_data["discount_price"]=input_data["price"]*0.75
print("input data shape", input_data.shape)
print(input_data.columns)

input data shape (48895, 16)
input data shape (48895, 17)
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'discount_price'],
      dtype='object')

In [74]:
import numpy as np
random_number=np.random.uniform(low=0, high=11, size=input_data.shape[0] )
print(random_number)
print(len(random_number))

[10.54650591  7.50797587  2.60996315 ...  7.67775896  6.81623993
  9.82098115]
48895

# Shuffle the data

In [77]:
input_data["random_number_col"]=random_number
print("Actual data \n", input_data.head())
input_data1=input_data.sort_values(by="random_number_col")
print("Data after shuffling \n", input_data1.head())

Actual data
      id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787
1  2595                             Skylit Midtown Castle     2845
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632
3  3831                   Cozy Entire Floor of Brownstone     4869
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976
4        Laura           Manhattan   East Harlem  40.79851  -73.94399

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19
1  Entire home/apt    225               1                 45  2019-05-21
2     Private room    150               3                  0         NaN
3  Entire home/apt     89               1                270  2019-07-05
4  Entire home/apt     80              10                  9  2018-11-19

   reviews_per_month  calculated_host_listings_count  availability_365  \
0               0.21                               6               365
1               0.38                               2               355
2                NaN                               1               365
3               4.64                               1               194
4               0.10                               1                 0

   discount_price  random_number_col
0          111.75          10.546506
1          168.75           7.507976
2          112.50           2.609963
3           66.75          10.150251
4           60.00           6.312460
Data after shuffling
              id                                              name   host_id  \
16526  13240737  Times Square / Broadway Area - Midtown Manhattan  74397192
22633  18310427                          A huge bedroom in Harlem  63417081
4827    3430612     Beautiful Brooklyn 3 bdrm in Prospect Heights  17289499
25790  20636966                    Beautiful Lower East Side Loft   1521723
18904  15018397               Peaceful Room in Dumbo Art Loft Too  37723496

      host_name neighbourhood_group     neighbourhood  latitude  longitude  \
16526     Glenn           Manhattan    Hell's Kitchen  40.76345  -73.99298
22633     Devon           Manhattan            Harlem  40.82348  -73.94581
4827      Laura            Brooklyn  Prospect Heights  40.67998  -73.96743
25790      Nick           Manhattan   Lower East Side  40.71470  -73.98994
18904      Anna            Brooklyn             DUMBO  40.70426  -73.98633

             room_type  price  minimum_nights  number_of_reviews last_review  \
16526     Private room     79               3                136  2019-06-26
22633     Private room     39              30                  5  2019-01-07
4827   Entire home/apt    140               3                 12  2017-09-04
25790  Entire home/apt    400               3                  5  2019-07-04
18904     Private room    125               2                 98  2019-06-29

       reviews_per_month  calculated_host_listings_count  availability_365  \
16526               3.65                               1                47
22633               0.24                               8               202
4827                0.20                               1                 4
25790               0.24                               1                26
18904               2.88                               2               164

       discount_price  random_number_col
16526           59.25           0.000511
22633           29.25           0.000768
4827           105.00           0.000906
25790          300.00           0.001462
18904           93.75           0.001783

In [80]:
input_data2=input_data.sample(n=input_data.shape[0])
print(input_data2.head())

             id                                               name    host_id  \
25576  20479561   Upper east side cozy apt available in September.  112176192
16325  13130565       Private bedroom in two bedroom apartment one   73124477
13682  10253159  Newly renovated house 4 bedroom. Minutes from NYC   10721093
27200  21499536           Sunny and cozy Upper West Side Apartment    8132596
32393  25350971  Charming apartment in Greenpoint Historic Dist...   41457105

       host_name neighbourhood_group      neighbourhood  latitude  longitude  \
25576  Catherine           Manhattan    Upper East Side  40.78269  -73.95288
16325  Alexander            Brooklyn      Crown Heights  40.67433  -73.94243
13682   Jonathan       Staten Island  Castleton Corners  40.61042  -74.12277
27200      Aniko           Manhattan    Upper West Side  40.78858  -73.97462
32393     Justin            Brooklyn         Greenpoint  40.73374  -73.95854

             room_type  price  minimum_nights  number_of_reviews last_review  \
25576  Entire home/apt    127               1                  0         NaN
16325     Private room     40               5                119  2019-05-31
13682  Entire home/apt    299               3                 49  2019-06-30
27200  Entire home/apt    170               3                 34  2018-04-01
32393  Entire home/apt    125               2                  0         NaN

       reviews_per_month  calculated_host_listings_count  availability_365  \
25576                NaN                               1                 0
16325               3.16                               2                 3
13682               1.91                               1               350
27200               1.66                               1                 0
32393                NaN                               1                 0

       discount_price  random_number_col
25576           95.25           2.514979
16325           30.00           5.430546
13682          224.25           3.796581
27200          127.50           5.474232
32393           93.75           4.304424

# Handling Duplicates

In [ ]:
#Are there any duplicate rows in the overall dataset?, if yes, how many?
#Are there any duplicates based on host_id?

In [82]:
sum(input_data.duplicated())

0

In [84]:
sum(input_data.duplicated(["host_id"]))

11438

In [85]:
input_data["dupes_col_host_id"]=input_data.duplicated(["host_id"])

In [86]:
input_data["dupes_col_host_id"]

0        False
1        False
2        False
3        False
4        False
         ...
48890     True
48891     True
48892    False
48893     True
48894    False
Name: dupes_col_host_id, Length: 48895, dtype: bool

In [88]:
print("Before drop" , input_data.shape)
input_data_nodup= input_data[input_data['dupes_col_host_id']==False]
print("After removing dupes" , input_data.shape)

Before drop (48895, 19)
After removing dupes (37457, 19)

In [90]:
print("Before drop" , input_data.shape)
input_data_nodup1=input_data.drop_duplicates(["host_id"])
print("After removing dupes" , input_data_nodup1.shape)

Before drop (48895, 16)
After removing dupes (37457, 16)

# Merging the datasets

In [91]:
#Import the AB_NYC_2019_Reviews.csv data. Attach ratings data to the input data.
review_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/python_5days/master/Day2_Files/Datasets/AB_NYC_2019_Reviews.csv")
review_data.shape

(38843, 8)

In [92]:
review_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38843 entries, 0 to 38842
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 38843 non-null  int64
 1   name               38837 non-null  object
 2   host_id            38843 non-null  int64
 3   host_name          38827 non-null  object
 4   number_of_reviews  38843 non-null  int64
 5   last_review        38843 non-null  object
 6   reviews_per_month  38843 non-null  float64
 7   Rating             38843 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 2.4+ MB

In [93]:
input_and_review_l=pd.merge(input_data,review_data, on=["id"], how="left")

In [94]:
print("input_data shape", input_data.shape)
print("review_data shape", review_data.shape)
print("input_and_review_l shape", input_and_review_l.shape)

input_data shape (48895, 16)
review_data shape (38843, 8)
input_and_review_l shape (48895, 23)

In [95]:
input_and_review_inner=pd.merge(input_data,review_data, on=["id"], how="inner")
print("input_data shape", input_data.shape)
print("review_data shape", review_data.shape)
print("input_and_review_inner shape", input_and_review_inner.shape)

input_data shape (48895, 16)
review_data shape (38843, 8)
input_and_review_inner shape (38843, 23)

In [96]:
input_and_review_right=pd.merge(input_data,review_data, on=["id"], how="right")
print("input_data shape", input_data.shape)
print("review_data shape", review_data.shape)
print("input_and_review_right shape", input_and_review_right.shape)

input_data shape (48895, 16)
review_data shape (38843, 8)
input_and_review_right shape (38843, 23)

In [97]:
input_and_review_outer=pd.merge(input_data,review_data, on=["id"], how="outer")
print("input_data shape", input_data.shape)
print("review_data shape", review_data.shape)
print("input_and_review_outer shape", input_and_review_outer.shape)

input_data shape (48895, 16)
review_data shape (38843, 8)
input_and_review_outer shape (48895, 23)

# Exporting the data

In [98]:
input_and_review_outer.to_csv("outer_join_data.csv")

In [99]:
input_and_review_inner.to_csv("inner_join_data.csv")